### ISSUE TITLE
Update pip?

### ISSUE THREAD

**Issue by jjreicher** [OpenShiftDemos/os-sample-python#2]
I realize this is slightly OT, but what is the best way to implement this project but update pip before it launches? My script requires dependencies that require pip 8.1, but default on the server is 7.x.

**Comment by GrahamDumpleton** [comment]
Add a file:

```
.s2i/environment
```

and in it add:

```
UPGRADE_PIP_TO_LATEST=1
```

For details of environment variables that can be set see:

* https://github.com/sclorg/s2i-python-container/blob/master/2.7/README.md

**Comment by jjreicher** [comment]
Perfect, thanks for the help!
