### ISSUE TITLE
Config.py clarification

### ISSUE THREAD

**Issue by jjreicher** [OpenShiftDemos/os-sample-python#3]
Apologies for another question posted as an issue, though perhaps useful to others (maybe?)--any info/resources for config options in the config.py file? 

The syntax seems designed for the OpenShift environment with lines like these: threads = int(os.environ.get('GUNICORN_THREADS', '1'))

How do I set error log levels (really the question I'm after)? My app is getting to the "booting worker with pid" step but then must be throwing some error but not reporting it.

Thanks again.

**Comment by GrahamDumpleton** [comment]
The ``config.py`` is standard configuration file format that gunicorn accepts. See the gunicorn documentation:

* http://docs.gunicorn.org/en/stable/configure.html

**Comment by jjreicher** [comment]
I guess what's unclear is the need for this all-caps GUNICORN_THREADS, for example, which is not in the gunicorn documentation.

**Comment by GrahamDumpleton** [comment]
It is just allowing you to override the default value by passing in an environment variable. The environment variable can be set in the deployment configuration in OpenShift.

* https://docs.openshift.com/container-platform/3.5/dev_guide/environment_variables.html
