### ISSUE TITLE
My application deployment is in pending state

### ISSUE THREAD

**Issue by nikhila05** [OpenShiftDemos/os-sample-python#4]
Hi, 

I've setup a sample python application by following this blog(https://blog.openshift.com/getting-started-python/). But the deployment status is in pending state only.

**Comment by GrahamDumpleton** [comment]
If you are using Online Starter, it has been having some issues which are still being resolved. You can track status at:

* https://status.starter.openshift.com/

To try and get past the issue, cancel the current deployment and start a new deployment. This can be done from the deployment configuration in the web console.

In future, if needing help for Online Starter, it is better to ask on StackOverflow of OpenShift list on Google Groups.

* https://groups.google.com/forum/#!forum/openshift
