### ISSUE TITLE
Question - what is config.py for?

### ISSUE THREAD

**Issue by jfmatth** [OpenShiftDemos/os-sample-python#7]
Hi Graham, 

Just curious, what is config.py for?  is this a flask "thing" or something in s2i?

thanks,

**Comment by GrahamDumpleton** [comment]
If you set ``APP_CONFIG`` environment variable to be ``config.py``, it will be passed as the config file to ``gunicorn`` if it is being used.

* https://github.com/sclorg/s2i-python-container/blob/master/3.6/s2i/bin/run#L88

**Comment by jfmatth** [comment]
Graham, thanks for the response.  I was premature in my question and didn't review the s2i stuff first.  Figured it out to match your response :).

thanks again, keep up the great work!
